export const stateDistrictsList = [
  {
    state: 'andhra pradesh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Andhra_Pradesh',
    remarks: 'list of districts has good details and more info',
    numberOfDistricts: '26',
    totalPopulation_2011: '49,577,103',
    populationPerDistrict: '1,906,812',
    regionId: 'in-s-andhra-pradesh',
  },
  {
    state: 'arunachal pradesh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Arunachal_Pradesh',
    numberOfDistricts: '28',
    totalPopulation_2011: '1,383,727',
    populationPerDistrict: '49,419',
    regionId: 'in-s-arunachal-pradesh',
  },
  {
    state: 'assam',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Assam',
    numberOfDistricts: '35',
    totalPopulation_2011: '31,205,576',
    populationPerDistrict: '891,588',
    regionId: 'in-s-assam',
  },
  {
    state: 'bihar',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Bihar',
    numberOfDistricts: '38',
    totalPopulation_2011: '104,099,452',
    populationPerDistrict: '2,739,459',
    regionId: 'in-s-bihar',
  },
  {
    state: 'chhattisgarh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Chhattisgarh',
    numberOfDistricts: '33',
    totalPopulation_2011: '25,545,198',
    populationPerDistrict: '774,097',
    regionId: 'in-s-chhattisgarh',
  },
  {
    state: 'goa',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Goa',
    numberOfDistricts: '2',
    totalPopulation_2011: '1,458,545',
    populationPerDistrict: '729,273',
    regionId: 'in-s-goa',
  },
  {
    state: 'gujarat',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Gujarat',
    numberOfDistricts: '33',
    totalPopulation_2011: '60,439,692',
    populationPerDistrict: '1,831,506',
    regionId: 'in-s-gujarat',
  },
  {
    state: 'haryana',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Haryana',
    numberOfDistricts: '22',
    totalPopulation_2011: '25,351,462',
    populationPerDistrict: '1,152,339',
    regionId: 'in-s-haryana',
  },
  {
    state: 'himachal pradesh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Himachal_Pradesh',
    numberOfDistricts: '12',
    totalPopulation_2011: '6,864,602',
    populationPerDistrict: '572,050',
    regionId: 'in-s-himachal-pradesh',
  },
  {
    state: 'jharkhand',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Jharkhand',
    numberOfDistricts: '24',
    totalPopulation_2011: '32,988,134',
    populationPerDistrict: '1,374,506',
    regionId: 'in-s-jharkhand',
  },
  {
    state: 'karnataka',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Karnataka',
    numberOfDistricts: '31',
    totalPopulation_2011: '61,095,297',
    populationPerDistrict: '1,970,816',
    regionId: 'in-s-karnataka',
  },
  {
    state: 'kerala',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Kerala',
    numberOfDistricts: '14',
    totalPopulation_2011: '33,406,061',
    populationPerDistrict: '2,386,147',
    regionId: 'in-s-kerala',
  },
  {
    state: 'madhya pradesh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Madhya_Pradesh',
    numberOfDistricts: '55',
    totalPopulation_2011: '72,626,809',
    populationPerDistrict: '1,274,155',
    regionId: 'in-s-madhya-pradesh',
  },
  {
    state: 'maharashtra',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Maharashtra',
    numberOfDistricts: '36',
    totalPopulation_2011: '112,374,333',
    populationPerDistrict: '3,121,509',
    regionId: 'in-s-maharashtra',
  },
  {
    state: 'manipur',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Manipur',
    numberOfDistricts: '16',
    totalPopulation_2011: '2,570,390',
    populationPerDistrict: '160,649',
    regionId: 'in-s-manipur',
  },
  {
    state: 'meghalaya',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Meghalaya',
    numberOfDistricts: '12',
    totalPopulation_2011: '2,966,889',
    populationPerDistrict: '247,241',
    regionId: 'in-s-meghalaya',
  },
  {
    state: 'mizoram',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Mizoram',
    numberOfDistricts: '11',
    totalPopulation_2011: '1,097,206',
    populationPerDistrict: '99,746',
    regionId: 'in-s-mizoram',
  },
  {
    state: 'nagaland',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Nagaland',
    numberOfDistricts: '16',
    totalPopulation_2011: '1,978,502',
    populationPerDistrict: '123,656',
    regionId: 'in-s-nagaland',
  },
  {
    state: 'odisha',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Odisha',
    numberOfDistricts: '30',
    totalPopulation_2011: '41,974,218',
    populationPerDistrict: '1,399,141',
    regionId: 'in-s-odisha',
  },
  {
    state: 'punjab',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Punjab,_India',
    numberOfDistricts: '23',
    totalPopulation_2011: '27,743,338',
    populationPerDistrict: '1,206,232',
    regionId: 'in-s-punjab',
  },
  {
    state: 'rajasthan',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Rajasthan',
    numberOfDistricts: '50',
    totalPopulation_2011: '68,548,437',
    populationPerDistrict: '1,370,969',
    regionId: 'in-s-rajasthan',
  },
  {
    state: 'sikkim',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Sikkim',
    numberOfDistricts: '6',
    totalPopulation_2011: '610,577',
    populationPerDistrict: '101,763',
    regionId: 'in-s-sikkim',
  },
  {
    state: 'tamil nadu',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Tamil_Nadu',
    numberOfDistricts: '38',
    totalPopulation_2011: '72,147,030',
    populationPerDistrict: '1,898,606',
    regionId: 'in-s-tamil-nadu',
  },
  {
    state: 'telangana',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Telangana',
    numberOfDistricts: '33',
    totalPopulation_2011: '35,003,674',
    populationPerDistrict: '1,060,717',
    regionId: 'in-s-telangana',
  },
  {
    state: 'tripura',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Tripura',
    numberOfDistricts: '8',
    totalPopulation_2011: '3,673,917',
    populationPerDistrict: '459,240',
    regionId: 'in-s-tripura',
  },
  {
    state: 'uttar pradesh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Uttar_Pradesh',
    numberOfDistricts: '75',
    totalPopulation_2011: '199,812,341',
    populationPerDistrict: '2,664,165',
    regionId: 'in-s-uttar-pradesh',
  },
  {
    state: 'uttarakhand',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Uttarakhand',
    numberOfDistricts: '13',
    totalPopulation_2011: '10,086,292',
    populationPerDistrict: '775,869',
    regionId: 'in-s-uttarakhand',
  },
  {
    state: 'west bengal',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_West_Bengal',
    numberOfDistricts: '23',
    totalPopulation_2011: '91,276,115',
    populationPerDistrict: '3,042,537',
    regionId: 'in-s-west-bengal',
  },
  {
    state: 'andaman and nicobar islands',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_the_Andaman_and_Nicobar_Islands',
    numberOfDistricts: '3',
    totalPopulation_2011: '380,581',
    populationPerDistrict: '126,860',
    regionId: 'in-s-andaman-and-nicobar-islands',
  },
  {
    state: 'chandigarh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/Chandigarh_district',
    numberOfDistricts: '1',
    totalPopulation_2011: '1,055,450',
    populationPerDistrict: '1,055,450',
    regionId: 'in-s-chandigarh',
  },
  {
    state: 'dadra nagar haveli, daman and diu',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Dadra_and_Nagar_Haveli_and_Daman_and_Diu',
    numberOfDistricts: '3',
    totalPopulation_2011: '586,956',
    populationPerDistrict: '195,652',
    regionId: 'in-s-dadra-nagar-haveli,-daman-and-diu',
  },
  {
    state: 'jammu and kashmir',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Jammu_and_Kashmir',
    numberOfDistricts: '20',
    totalPopulation_2011: '12,258,093',
    populationPerDistrict: '612,905',
    regionId: 'in-s-jammu-and-kashmir',
  },
  {
    state: 'ladakh',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Ladakh',
    numberOfDistricts: '7',
    totalPopulation_2011: '290,492',
    populationPerDistrict: '41,499',
    regionId: 'in-s-ladakh',
  },
  {
    state: 'lakshadweep',
    wikipedia_page: 'https://en.wikipedia.org/wiki/Lakshadweep_district',
    numberOfDistricts: '1',
    totalPopulation_2011: '64,473',
    populationPerDistrict: '64,473',
    regionId: 'in-s-lakshadweep',
  },
  {
    state: 'delhi',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Delhi',
    numberOfDistricts: '11',
    totalPopulation_2011: '16,787,941',
    populationPerDistrict: '1,526,176',
    regionId: 'in-s-delhi',
  },
  {
    state: 'puducherry',
    wikipedia_page: 'https://en.wikipedia.org/wiki/List_of_districts_of_Puducherry',
    numberOfDistricts: '4',
    totalPopulation_2011: '1,247,953',
    populationPerDistrict: '311,988',
    regionId: 'in-s-puducherry',
  },
];
