export const publicServiceDomainsData = [
  {
    id: 1,
    name_english: "Defence",
    image: "https://d7ge4det5w05u.cloudfront.net/d6198b80-f048-4514-be87-d485b40361ea.png",
    exampleOrganisations: ["Ministry of defence", "DRDO", "Indian Army", "Indian Navy", "Indian Air Force"],
  },
  {
    id: 6,
    name_english: "Space",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/bb5cfd57-cb8d-47e5-af0b-06e593ba1aed.png",
    imageLicence: "CC",
    exampleOrganisations: ["Department of Space", "Indian Space Research Organisation"],
  },
  {
    id: 9,
    name_english: "Foreign Affairs",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/ecebf5b0-7105-45d8-8a3e-50a73e04193f.png",
    exampleOrganisations: [
      "Ministry of External Affairs",
      "Embassies of India",
      "Development Partnership Administration",
      "Emigration Policy & Welfare",
      // 'Foreign Service Institute',
    ],
  },
  {
    id: 21,
    name_english: "Healthcare",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/8b23426f-e6dd-4fb0-a73b-24bc8b98b625.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Health and Family Welfare",
      "Department of Health Research",
      "Indian Council of Medical Research",
      // 'National Health Authority',
      // 'National Health Systems Resource Centre',
      "National Institute of Medical Statistics",
      // 'All India Institute of Medical Sciences',
    ],
  },
  {
    id: 3,
    name_english: "Education",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/fcaa9595-8db1-43e3-8f7a-5575ead0efa9.png",
    exampleOrganisations: [
      "Ministry of Education",
      "Department of School Education & Literacy",
      "Department of Higher Education",
      "University Grants Commission",
      // 'National Council of Educational Research and Training',
      // 'National Institute of Open Schooling',
      // 'National Institute of Educational Planning and Administration',
    ],
  },
  {
    id: 10,
    name_english: "Railways",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/30960e08-4b62-4f67-b74c-d3b664aea789.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Railways",
      "Indian Railways",
      "Railway Board",
      "Dedicated Freight Corridor Corporation of India",
      "Railway Protection Force",
      // 'Railway Claims Tribunal',
    ],
  },
  {
    id: 13,
    name_english: "Road Transportation",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/92fcc863-331d-4c4e-86bf-dde6c60ac17d.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Road Transport and Highways",
      "National Highways Authority of India",
      // 'National Highways and Infrastructure Development Corporation',
      "National Road Safety Board",
    ],
  },
  {
    id: 14,
    name_english: "Ports & Shipping",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/5675e1d6-2a01-46c1-b600-004decfa7e58.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Ports, Shipping and Waterways",
      "Directorate General of Shipping",
      "Indian Ports Association",
      "Indian Maritime University",
      // 'National Maritime Heritage Complex',
    ],
  },
  {
    id: 15,
    name_english: "Civil Aviation",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/c339d659-8e34-4b1f-82fb-bb6d4cf453aa.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Civil Aviation",
      "Directorate General of Civil Aviation",
      "Airports Authority of India",
      // 'Airports Economic Regulatory Authority of India',
    ],
  },
  {
    id: 7,
    name_english: "Agriculture & Fishing",
    institutionOwnershipLevels: ["UNION", "STATE"],
    lawMakingLevels: ["STATE"],
    image: "https://d7ge4det5w05u.cloudfront.net/b26b273f-41e1-44fd-a86d-463d0e617576.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Agriculture & Farmers Welfare",
      // 'Department of Agriculture, Cooperation & Farmers Welfare',
      // 'Department of Agricultural Research & Education',
      "Department of Animal Husbandry & Dairying",
      "Department of Fisheries",
      "Department of Agricultural Marketing",
    ],
  },
  {
    id: 8,
    name_english: "Energy",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/35bb0111-9588-4e77-9dba-2f21077cd246.png",
    exampleOrganisations: [
      "Ministry of Power",
      "Ministry of New and Renewable Energy",
      "Power Grid Corporation of India",
      "Central Electricity Authority",
      // 'Central Electricity Regulatory Commission',
    ],
  },
  {
    id: 18,
    name_english: "Petroleum, Natural Gas",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/25d83e01-74f7-4f24-863e-83a2bee23fd4.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Petroleum and Natural Gas",
      "Directorate General of Hydrocarbons",
      // 'Petroleum and Natural Gas Regulatory Board',
      "Petroleum Planning and Analysis Cell",
      "Oil and Natural Gas Corporation",
    ],
  },
  {
    id: 5,
    name_english: "Minerals",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/a85d0bf7-353b-451c-8d8c-1faf34e01ac0.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Ministry of Mines",
      "Ministry of Coal",
      "Indian Bureau of Mines",
      "Coal India Limited",
      "National Mineral Development Corporation",
    ],
  },
  {
    id: 23,
    name_english: "Industries and Trade",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/7be1e6e2-1b13-47ba-9a7d-68c51bf8ae82.png",
    exampleOrganisations: [
      "Ministry of Commerce and Industry",
      "Ministry of Corporate Affairs",
      // 'Department for Promotion of Industry and Internal Trade',
      "Department of Commerce",
      "DPIIT",
      "Directorate General of Foreign Trade",
    ],
  },
  {
    id: 32,
    name_english: "Labour",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/d59cce96-0f26-406c-aa9a-ecc20b957a9b.png",
    exampleOrganisations: [
      "Ministry of Labour and Employment",
      "Directorate General of Employment",
      "Directorate General of Training",
      "Employees’ State Insurance Corporation",
    ],
  },
  {
    id: 2,
    name_english: "Government Finances",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/be5ebfed-b323-4601-ab48-8c71d2916f50.png",
    exampleOrganisations: [
      "Ministry of Finance",
      "Department of Economic Affairs",
      "Department of Expenditure",
      "Department of Revenue",
      // 'Department of Investment and Public Asset Management',
      // 'Department of Financial Services',
    ],
  },
  // {
  //   id: 17,
  //   name_english: 'Banking & Insurance',
  //   institutionOwnershipLevels: ['UNION'],
  //   lawMakingLevels: ['UNION'],
  //   image: 'https://d7ge4det5w05u.cloudfront.net/639a3f58-503f-4613-a6d9-89a59e582661.png',
  // },
  {
    id: 24,
    name_english: "Taxes & Duties",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/5295ea59-9c70-4c9d-a170-667889b7d093.png",
    imageLicence: "CC",
    exampleOrganisations: [
      "Central Board of Direct Taxes",
      // 'Central Board of Indirect Taxes and Customs',
      "Central Board of Excise and Customs",
      "Income Tax Department",
    ],
  },
  {
    id: 27,
    name_english: "Stock & futures markets",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/e0552249-9a92-4c9c-acf9-f18dc02cd856.png",
    exampleOrganisations: [
      "Securities and Exchange Board of India",
      "National Stock Exchange of India",
      "Bombay Stock Exchange",
      "Multi Commodity Exchange of India",
    ],
  },
  {
    id: 33,
    name_english: "Law and Justice",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/093c6d6f-4f1e-459c-87fb-fc0d4c89482f.png",
    exampleOrganisations: [
      "Ministry of Law and Justice",
      "Supreme Court of India",
      "High Courts of India",
      // 'District Courts of India',
      "National Company Law Tribunal",
      // 'National Company Law Appellate Tribunal',
    ],
  },
  {
    id: 19,
    name_english: "Elections",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/3e5357f5-6583-4f81-b3ee-1955d34a1151.png",
    imageLicence: "CC",
    exampleOrganisations: ["Election Commission of India", "State Election Commissions"],
  },
  {
    id: 20,
    name_english: "Law Enforcement",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/1c82b600-1518-4ce4-b335-a166f2971003.png",
    exampleOrganisations: [
      "Ministry of Home Affairs",
      "State Police Forces",
      "Central Reserve Police Force",
      "Border Security Force",
      // 'Central Industrial Security Force',
    ],
  },
  {
    id: 34,
    name_english: "Public Broadcasting",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/cv49273f-4sd1-44fd-c24d-463d0e615fg8.png",
    exampleOrganisations: [
      "Ministry of Information and Broadcasting",
      "Prasar Bharati",
      "All India Radio",
      "Central Board of Film Certification",
      "Film and Television Institute of India",
    ],
  },
  {
    id: 16,
    name_english: "Communication",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/ff1e0184-3198-437c-a6b8-3e6a03aae249.png",
    exampleOrganisations: [
      "Ministry of Communications",
      "Department of Telecommunications",
      "Department of Posts",
      "Telecom Regulatory Authority of India",
    ],
  },
  {
    id: 28,
    name_english: "History & Culture",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/02abaac9-1061-4d30-8b69-dc71b029cc58.png",
    exampleOrganisations: [
      "Ministry of Culture",
      "Archaeological Survey of India",
      "National Archives of India",
      "National Museum Institute",
    ],
  },
  {
    id: 38,
    name_english: "Rural Development",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/1234b600-1518-sdfg-b335-a166f297qssz.png",
    exampleOrganisations: [
      "Ministry of Rural Development",
      "Department of Rural Development",
      "Department of Land Resources",
      // 'National Institute of Rural Development and Panchayati Raj',
    ],
  },
  {
    id: 39,
    name_english: "Urban Development",
    institutionOwnershipLevels: ["UNION"],
    lawMakingLevels: ["UNION"],
    image: "https://d7ge4det5w05u.cloudfront.net/xdfr0184-31e8-wt7c-a238-3e6a03aa3do0.png",
    exampleOrganisations: [
      "Ministry of Housing and Urban Affairs",
      "Department of Urban Development",
      "Central Public Works Department",
      // 'National Buildings Construction Corporation',
      "National Institute of Urban Affairs",
    ],
  },
];
